[project]
name = "otus-mlops-dvc-lesson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.12"
dependencies = [
    "dvc[s3]==3.59.2",
    "loguru==0.7.3",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
]
